### ISSUE TITLE
数据集文件不全，数据中没有这些txt文件

### ISSUE THREAD

**Issue by intelligence66** [chengche6230/ReST#1]
![image](https://github.com/chengche6230/ReST/assets/143588247/4c8f9d7c-b57c-4616-a3aa-b23ff879e4e7)

**Comment by chengche6230** [comment]
Hi,

For CAMPUS and PETS09, we use third-party annotation in our settings.
ref: https://bitbucket.org/merayxu/multiview-object-tracking-dataset/src/master/

**Comment by intelligence66** [comment]
好的，谢谢

**Comment by intelligence66** [comment]
![dc6d30331a887fed4726460732d17b0](https://github.com/chengche6230/ReST/assets/143588247/f49fd35c-4fc8-4981-a9cb-d4cb1513790f)
这里面的数据下载不了呢

**Comment by chengche6230** [comment]
Hi, 

If the issue still remains, you can try to download each file individually.
Download the ".mp4" and ".txt" files in the sequence you need.

**Comment by intelligence66** [comment]
![image](https://github.com/chengche6230/ReST/assets/143588247/98dabfeb-9324-4790-a99a-114a21e1117f)
这里面也没有下载的按钮呢

**Comment by chengche6230** [comment]
Hi, 

If still cannot download the whole repo., try to click "..." -> "Open raw" to access both ".mp4" and ".txt" files.
Contact with them if encounter other issues, thanks.

**Comment by intelligence66** [comment]
![image](https://github.com/chengche6230/ReST/assets/143588247/04f9f995-71f7-468a-a498-dfac4b68958e)
最主要的问题是，下载的压缩包打不开，显示文件已被破坏，可以分享一下你们下载好的数据集吗？

**Comment by chengche6230** [comment]
Hi,

The following link is the downloaded dataset:
https://drive.google.com/drive/folders/1nBSkIB9EKLswLfYJ6RaTIkYdVwUpq8XU?usp=sharing

**Comment by intelligence66** [comment]
好的，谢谢您的分享。

**Comment by intelligence66** [comment]
您好，还有一些问题想请教您，可以给个联系方式吗？方便沟通。

**Comment by chengche6230** [comment]
Sry for the late reply, you can directly contact me with the email: chengche6230@gmail.com
I'll reply it asap.

**Comment by intelligence66** [comment]
好的，谢谢您
