### ISSUE TITLE
Suggestions for bad temporal inference and illogical spatial assignments within the scene

### ISSUE THREAD

**Issue by deepsworld** [chengche6230/ReST#16]
Thank you for sharing your great work. We are trying to use the ReST code and framework on MMPTrack dataset which has fully overlapping camera views and larger training data size than Wildtrack. The training and inference code runs fine but the results are not good. We did not modify the code other than the dataset to allow it to work with this custom dataset. Can you please provide some suggestions or advice on the following: 

1. Frame wise tracking in single camera view results in tracks that change almost every frame. 
2. Spatial assignments across cameras somewhat works but assigns same track ID to multiple person in the same camera view. 

Please find 5 annotated frame sequence (frame #21-25, each image contains the grid of all views) from the MMPTrack pretrained model for your reference.  We use the same config as Wildtrack and the model predictions and training is with groundtruth boxes

![grid_21](https://github.com/chengche6230/ReST/assets/35742688/61aa0f12-fafa-4061-afb3-4cc1e932cf1e)
![grid_22](https://github.com/chengche6230/ReST/assets/35742688/0b61a283-3a1d-4bb1-8605-8caa39d3114c)
![grid_23](https://github.com/chengche6230/ReST/assets/35742688/f0015a52-e1d0-48b5-ba5a-969316d313d8)
![grid_24](https://github.com/chengche6230/ReST/assets/35742688/f041051f-edae-4dbe-bd9b-e39022d7bf3a)
![grid_25](https://github.com/chengche6230/ReST/assets/35742688/383034fd-61a3-43b6-b217-4dadd6e07e80)

Thanks,
Deep

**Comment by chengche6230** [comment]
Hi

Thanks for your interest in our research. Our model is mostly rely on the feature of geometry position as claimed in the paper. You need to make sure the projection of the same person is close enough while the projection of different people is far away by refining the homography matrix instead of using homography from other datasets. It may not work when the region is too small and crowded.

Best
