### ISSUE TITLE
For custom dataset (inference only), how to obtain homography data?

### ISSUE THREAD

**Issue by truongsinh** [chengche6230/ReST#18]
Hi, for a customer dataset (inference only), how can I calculate homography, especially if I only have access to the videos themeselves, and not the physical setup of the cameras?

**Comment by chengche6230** [comment]
Hi,

Please refer to: 
https://github.com/chengche6230/ReST/issues/9#issuecomment-2007662379
https://github.com/chengche6230/ReST/issues/12#issuecomment-2036559752
