### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by jingliang0910** [chengche6230/ReST#19]
hi，how can i download CAMPUS and PETS09-S2L1 datasets？I find their website can not be opened.

**Comment by chengche6230** [comment]
Access the third-party annotation files here: https://drive.google.com/drive/folders/1nBSkIB9EKLswLfYJ6RaTIkYdVwUpq8XU?usp=sharing
For the original datasets, please mail the author. Thanks.

**Comment by jingliang0910** [comment]
ohhh！，thanks！

**Comment by jingliang0910** [comment]
ohhh！，thanks！

**Comment by SongTang-x** [comment]
Hello, have you downloaded the PETS09-S2L1 dataset? I also want to download this dataset. Can you give me some tips?

**Comment by SongTang-x** [comment]
@jingliang0910
