### ISSUE TITLE
the images of CAMPUS and PETS datasets

### ISSUE THREAD

**Issue by jingliang0910** [chengche6230/ReST#22]
![image](https://github.com/chengche6230/ReST/assets/133879282/a16619c4-1abb-46be-9163-849aea145d61)
how can I prepare the images of CAMPUS and PETS datasets?  In CAMPUS of your provided datasets, no existing image ，only some videos. How can I process these videos?
I have used your "preprocess" function, but no image produced.

**Comment by chengche6230** [comment]
Hi,

You can extract each frames of video by `load_videos( )` function in `preprocess.py`, or by your own utility code. Just prepare the images with the same naming pattern.
