### ISSUE TITLE
Datasets 

### ISSUE THREAD

**Issue by harshap-ai** [chengche6230/ReST#4]
Hello Cheng, 
This is a really neat work! I was hoping to replicate this but finding it difficult to get the datasets. Just a quick question: 

I see that you've given a link to your google drive with downloaded datasets in #1. I have no issues with CAMPUS, but I see EPFL instead of Wildtrack, and there's no frames/videos for PETS09. Can you please clarify on that?

**Comment by chengche6230** [comment]
Hi, sry for the late reply. (Just back from ICCV)

The link is the 3rd party annotation files for CAMPUS, PETS09, and EPFL.
You need to access their official website to download the image frames for the original video sequences.
As for Wildtrack, both image frames and annotation files are already complete, no need to download via 3rd pt.

Best,
Cheng

**Comment by harshap-ai** [comment]
Hello Cheng, thanks for your reply. Hope you had a great time @ Paris. 

I have a couple of questions: 
1. You haven't used the EPFL dataset for training/testing, right? Because, your paper only mentions 3 datasets - Wildtrack, CAMPUS and PETS09. 
2. I don't see a link to Wildtrack dataset in the google drive link you've posted in Issue #1 (https://drive.google.com/drive/folders/1nBSkIB9EKLswLfYJ6RaTIkYdVwUpq8XU). Can you please furnish the processed dataset as you've used it? 

Thanks, 
Harish

**Comment by chengche6230** [comment]
Hi Harish,

1. Yes, we didn't include EPFL in our experiments although that third-party provided it.
2. That link is for the third-party annontation files of CAMPUS, EPFL, and PETS09, not for Wildtrack. As for Wildtrack, please refer to [this official link](https://www.epfl.ch/labs/cvlab/data/data-wildtrack/).

Best,
Cheng

**Comment by harshap-ai** [comment]
Perfect. If possible, would recommend you to update the Readme.md file with these links. 

Closing this issue, thank you!
