### ISSUE TITLE
Camera detection

### ISSUE THREAD

**Issue by ckysohandsome** [chengche6230/ReST#8]
Hello，thank you very much for sharing this code. Sorry to bother you. Could you please advise me on how to use the camera for real-time detection after training my weights? Could you please provide some detailed instructions? Thank you.

**Comment by chengche6230** [comment]
Hi,

You also need a real-time object detector to detect objects in the frame first as the input of our tracker. For the cross-camera association, we also need the camera calibration to calculate the projection of each object.

**Comment by ckysohandsome** [comment]
> Hi,
> 
> You also need a real-time object detector to detect objects in the frame first as the input of our tracker. For the cross-camera association, we also need the camera calibration to calculate the projection of each object.

Hello, I'm very sorry to have replied to you so late! I really appreciate your taking the time out of your busy schedule to reply to my question! I'm sorry to disturb you again, as I've just started learning deep learning and am still a beginner. I recently tried to implement real-time detection by referring to other code, but failed. So, I would like to refer to your detection code if possible. Could you please send the code to my email? I'm also willing to provide some compensation. Here is my email: cky11082019@163.com. I will use this for my own learning and not for any profit. Thank you very much for your help! If you are not willing to, I hope to be able to communicate with you again.

**Comment by chengche6230** [comment]
Hi,

Our research mostly focuses on the data association stage, not on the detection stage. We use source detection as our model's input, i.e. groundtruth detection, detection from YOLO or other multi-view detectors such as MVDeTr. If you want to develop an end-to-end MOT tracker, refer to other research for more infomation! For further discussion, feel free to contact me via email: chengche6230@gmail.com

Thanks.

**Comment by ckysohandsome** [comment]
> Hi,
> 
> Our research mostly focuses on the data association stage, not on the detection stage. We use source detection as our model's input, i.e. groundtruth detection, detection from YOLO or other multi-view detectors such as MVDeTr. If you want to develop an end-to-end MOT tracker, refer to other research for more infomation! For further discussion, feel free to contact me via email: [chengche6230@gmail.com](mailto:chengche6230@gmail.com)
> 
> Thanks.

Thank you very much again for your guidance! Please forgive me for the disturbance, your guidance has been very helpful to me! I hope we can communicate again ！

**Comment by Mr-Akbari** [comment]
Hi @chengche6230  @ckysohandsome , 
I want to develop an end-to-end MOT tracker based on this work. Can you help me how to merge real-time YOLOX object detection with ReST?
